### ISSUE TITLE
redo build broken?

### ISSUE THREAD

**Issue by stereosteve** [ianthehenry/bauble.studio#10]
Running `redo` on both osx + linux and I get:

```
redo  all
redo    build/public.tree
redo: no rule to redo 'main.css{,.checksum}'
redo    build/public.tree (exit 1)
redo  all (exit 1)
```

I see from other comments this project is on the back burner... but was wondering if you could provide any quick pointers on running locally.

Thanks!

**Comment by ianthehenry** [comment]
Oh no! I suspect this is the result of my sinfully using bash-specific features in a shell script that doesn't specify that it's bash, and your default shell being more POSIX-compliant. I *think* I pushed a fix, could you try again with the latest commit?

**Comment by stereosteve** [comment]
Thanks!  The `redo` works now.

On linux machine everything came up and worked.

On M1 mac I get:

<img width="889" alt="image" src="https://github.com/ianthehenry/bauble.studio/assets/97163/287d3bfb-84f7-421b-8e4d-e39fceb22e48">

I'm not super familiar with emcc, but suspect some wasm arch target stuff might be needed?

Anyway this is enough to tinker... thanks again.

**Comment by ianthehenry** [comment]
Hmmm, that error *could* indicate that your installed Janet is a different version than Bauble's Janet (yeah there's nothing keeping them in sync which is bad.) What is your Janet version? `janet -v`? If it's out of sync with `cat build/janet/janet-version` then you *could* see this error. Upgrading both to the latest might resolve it.

**Comment by stereosteve** [comment]
That makes sense... upgrading system janet fixed it thanks!
